### ISSUE TITLE
Set code coverage gates to fail CI checks if coverage drops below a given threshold. 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#2803]
From C: 

```
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: Check line coverage
    inputs:
      checkCoverage: true
      coverageFailOption: fixed
      coverageType: line
      # 90% minimum line coverage
      coverageThreshold: 90
    condition: eq(variables['AZ_SDK_CODE_COV'], 1)

  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: Check branch coverage
    inputs:
      checkCoverage: true
      coverageFailOption: fixed
      coverageType: branch
      # 70% minimum branch coverage
      coverageThreshold: 70
    condition: eq(variables['AZ_SDK_CODE_COV'], 1)
```

Proposed coverage amounts (@RickWinter): 
* 60% branch coverage
* 90% line coverage
