### ISSUE TITLE
Azure Storage should define CMakeTestOptions in it's ci.yml file.

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#4774]
**Describe the bug**
Currently the Azure CI pipelines have a mechanism to verify that the vcpkg configuration for each package is correctly authored.

This functionality depends on the service having the following fields in their ci.yml file:
```yaml
      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
```

Storage does not appear to have this, so the logic which ensures that the storage packages can be generated from the individual package directories is not enabled.

As a result, there are built-time errors which will occur if you attempt to run cmake from the storage package directories.

The long term goal for the Azure C++ SDK is to move to a model closer to that of the other Azure SDKS and enable building in each package individually to avoid the monolithic all-repo builds which are currently the solution. 

By not having a `CMakeTestOptions` field in the ci.yml file, the mechanisms in place to verify this functionality are disabled for storage.
